// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhyxppgemxigqhjphtrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoeXhwcGdlbXhpZ3FoanBodHJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTI1MjcsImV4cCI6MjA2ODE2ODUyN30.5KyFHkJgifl3W8zCn6gDjBJBArL0pZN4td2Ik0tIlYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});